### ISSUE TITLE
Ship 0.9.0

### ISSUE THREAD

**Issue by kenperkins** [pkgcloud/pkgcloud#207]
I wanted to put on paper my concrete list of tasks for 0.9.0.
- [x] Create 0.9.0 working branch
- [x] Refactor openstack extensions currently in compute provider
- [x] Rename key `os-floating-ip` methods on openstack compute provider to align with package norms
- [x] Refactor Rackspace Storage to be openstack swift compatible #213
- [x] Fix piping for storage upload/download #195
- [x] Properly figure out bootstrapping refactor with @mmalecki #204, #222
- [x] Refactor openstack identity to not parse at authorization time #208 
- [x] Add `os-networks` extension to openstack compute provider #226
- [x] Add Docs for Openstack #217
### Punt list
- [ ] Refactor examples to be functional, use environment variables for credentials #212
- [ ] Determine an appropriate mechanism to handle provider specific API extensions #232
  ...

Anything else?
