### ISSUE TITLE
Discuss what to lint?

### ISSUE THREAD

**Issue by kenperkins** [pkgcloud/pkgcloud#360]
Possible candidates for enforcing
- [x] `curly` require curly brackes for loops, conditionals #363
- [ ] `eqeqeq` require `===` and `!==`
- [x] `freeze` prohibit overwriting prototype on native objects #362 
- ~~`indent` set a specific tab width~~
- [x] `latedef` prohibit variable use before definition #370
- [x] `newcap` require capitalization of variables invoked with `new` #364
- [x] `noarg` prohibit `arguments.caller` and `arguments.callee` #365
- [x] `noempty` prohibit empty blocks, i.e. sloppy code #366
- [x] `quotmark` enforce use of quotes, I'd prefer `single`, see #360
- [x] `undef` prevent use of undefined variables #373
- [x] `unused` prevent unused but defined variables #371
